#!/usr/bin/env python3
"""Generate the close's veil: the calendar ring crossing the wordmark.

    python Source/tools/make-poster-veil.py [--self-test]

Writes Source/figures/poster-veil.svg, spliced by build-site.py at
<!--#include poster-veil--> inside the close's mark paragraph, and positioned
by .poster-veil in styles.css. Register the include there and the figure row
in verify-figures.py when you touch this.

WHY THIS EXISTS. The close already fuses the page's brand and its machine -
the wordmark's feet stand in the horizon's bead line, the crown rises behind
the letters - but every crossing so far leaves the LETTERS on top: type above
art, always, in every layer. The one reference pattern still unadapted is the
close that ends with the mark partly eclipsed by an illustration, so brand and
drawing read as one composed thing rather than type with a background. This is
that pattern in Istor's own material: a second pass of the disputed ring -
the page's oldest argument, 354 versus 355 - drapes across the letters'
middle, its beads IN FRONT of the type, so the wordmark sits inside the
machine the way the machine sits inside the page.

WHY IT IS HONEST. Nothing new is claimed. The beads are the same 355-hole
dashed-circle arithmetic as the horizon below them (same count, same
one-circle method, its apex bead again the disputed 355th, again in the
plate's --azure). The count is the figure's content; the radius and the apex
height are composition. The canvas: y=0 is the letters' cap line by CSS
contract (see the stylesheet note), so the apex at y=80 crosses the letters'
middle at every width the clamp renders - a fraction of the mark's own box,
not a pixel guess.

WHY THE LETTERS STAY READABLE. The beads cross at 0.5 opacity in the field's
own ink - the same value the horizon's beads carry - and the wordmark's halo
(the ::before rim) already puts the field's base colour around every glyph.
What the veil adds is intersection, not occlusion: the word is still the
subject, but the ring now passes THROUGH it, and the eye reads one machine.

THE CANOPY CURVE. The circle's centre sits BELOW its apex, so the bead line
is highest over the word's centre and falls away across the flanks - a canopy
rather than an arch. At R=2600 the drop is 12 units at the word's edge and
102 at the frame's, so the crossing is densest mid-word and lifts toward the
edges: the veil parts where the letters end.

SELF-TEST. The invariants a doctored copy would break: exactly 355 holes on
the full circle (decoded from the dash arithmetic, not counted from elements),
the apex bead present in --azure at the apex, the canopy geometry (drop
increasing with distance from centre, apex the line's highest point), no hex
anywhere, and the class name the stylesheet positions.

Standard library only.
"""

import gzip
import math
import re
import sys
from pathlib import Path

VB_W, VB_H = 1440, 420   # y=0 is the letters' cap line; see the stylesheet
APEX_Y = 80.0            # the veil's crown: mid-letters at every clamp size
CX = VB_W / 2.0

R = 2600.0               # the canopy. See THE CANOPY CURVE above.
CY = APEX_Y + R          # centre below the apex: the line drops away from it

HOLES = 355              # the plate's count, carried unchanged
DOT = 7.0                # the horizon's own bead diameter
PITCH = 2 * math.pi * R / HOLES
GAP = PITCH - 0.02

# Same rule as the horizon: a circle path starts at 3 o'clock and the dashes
# run clockwise, so this rotation lands the LAST hole at 12 o'clock. The
# disputed 355th hole is the apex bead here, as it is the horizon's.
ALPHA = math.degrees((HOLES - 0.5) * PITCH / R)
THETA = -90.0 - ALPHA

# How far the canopy falls by the frame's edge, printed as the check.
half = VB_W / 2.0
EDGE_Y = CY - math.sqrt(R * R - half * half)


svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {VB_W} {VB_H}"
     class="poster-veil" aria-hidden="true" focusable="false">
  <!-- The close's veil: the calendar ring's 355 holes crossing the wordmark.
       Generated by Source/tools/make-poster-veil.py - do not hand-edit. The
       canvas contract: this svg's y=0 is the letters' cap line, positioned by
       .poster-veil in styles.css as a fraction of the mark's own box. The
       apex bead is the disputed 355th, in the plate's --azure, exactly as on
       the horizon below. -->
  <g>
    <!-- The limb, four stacked strokes of one circle, widest and faintest
         first: the horizon's own recipe, so the two limbs read as one
         material. Every stroke fades to nothing before the frame's edge. -->
    <circle cx="{CX:g}" cy="{CY:.1f}" r="{R:g}" fill="none"
            stroke="var(--field-ink)" stroke-width="44" stroke-opacity="0.05"/>
    <circle cx="{CX:g}" cy="{CY:.1f}" r="{R:g}" fill="none"
            stroke="var(--field-ink)" stroke-width="20" stroke-opacity="0.075"/>
    <circle cx="{CX:g}" cy="{CY:.1f}" r="{R:g}" fill="none"
            stroke="var(--field-ink)" stroke-width="8" stroke-opacity="0.11"/>
    <circle cx="{CX:g}" cy="{CY:.1f}" r="{R:g}" fill="none"
            stroke="var(--field-ink)" stroke-width="2.4" stroke-opacity="0.34"/>
  </g>

  <!-- All 355 holes along that line, one dashed circle, IN FRONT of the
       letters: this element is the veil. The figure it is spliced into carries
       the z-order; the ink is the field's, so both worlds re-ink it. -->
  <circle cx="{CX:g}" cy="{CY:.1f}" r="{R:g}" fill="none"
          stroke="var(--field-ink)" stroke-width="{DOT:g}" stroke-linecap="round"
          stroke-opacity="0.5" stroke-dasharray="0.02 {GAP:.5f}"
          transform="rotate({THETA:.5f} {CX:g} {CY:.1f})"/>

  <!-- The disputed hole, at the apex, in the plate's --azure: the one piece
       of information the ring carries, as it is on the plate and the horizon. -->
  <circle cx="{CX:g}" cy="{APEX_Y:g}" r="{DOT * 0.72:.2f}" fill="var(--azure)"/>
</svg>
'''


def self_test() -> int:
    worst = 0
    hexes = re.findall(r"#[0-9a-fA-F]{3,8}\b", svg)
    dots = []
    for k in range(HOLES):
        a = math.radians(THETA + 90.0 + math.degrees((k + 0.5) * PITCH / R))
        dots.append((CX + R * math.cos(a), CY + R * math.sin(a)))

    def check(label, good, detail=""):
        nonlocal worst
        print("  %s  %s%s" % ("ok  " if good else "FAIL", label,
                              (" " + detail) if detail else ""))
        if not good:
            worst = 1

    in_frame = [(x, y) for x, y in dots if 0 <= x <= VB_W and 0 <= y <= VB_H]
    check("355 holes on the full circle", len(dots) == HOLES)
    check("%d beads in frame" % len(in_frame), len(in_frame) > 20,
          "found %d" % len(in_frame))

    # The canopy: apex the highest in-frame point of the bead line; the line
    # falls as distance from centre grows, monotonic on both flanks.
    apex_y = min(y for _, y in in_frame)
    check("apex is the line's crown", abs(apex_y - APEX_Y) < 0.5,
          "crown y=%.1f" % apex_y)
    left = sorted((x, y) for x, y in in_frame if x < CX)
    right = sorted((x, y) for x, y in in_frame if x >= CX)
    mono_l = all(left[i][1] >= left[i + 1][1] - 1e-6 for i in range(len(left) - 1))
    mono_r = all(right[i][1] <= right[i + 1][1] + 1e-6 for i in range(len(right) - 1))
    check("the canopy falls monotonically to both edges", mono_l and mono_r)
    check("canopy drop by the frame edge is %.0f units" % (EDGE_Y - APEX_Y),
          90 < EDGE_Y - APEX_Y < 115, "measured %.1f" % (EDGE_Y - APEX_Y))

    # The mark's crossing: at the word's half-width (~250 units) the line is
    # inside the letters (cap 0, baseline 154 at the design size).
    drop_word = (CY - math.sqrt(R * R - 250 ** 2)) - APEX_Y
    check("crosses mid-letters at the word's flanks",
          0 < APEX_Y + drop_word < 154, "flank y=%.0f" % (APEX_Y + drop_word))

    check("no hex colour", not hexes, str(hexes[:3]))
    check("class is the one the stylesheet positions",
          'class="poster-veil"' in svg)
    check("the disputed bead is the azure one at the apex",
          'cy="%g" r="%s" fill="var(--azure)"' % (APEX_Y, f"{DOT * 0.72:.2f}") in svg)

    if worst == 0:
        print("poster-veil self-test ok: 355 holes, canopy geometry, azure "
              "apex, token inks, stylesheet class")
    return worst


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        sys.exit(self_test())
    out = Path(__file__).resolve().parent.parent / "figures" / "poster-veil.svg"
    out.write_text(svg, encoding="utf-8", newline="\n")
    print(f"veil           R={R:g}  apex y={APEX_Y:g}  falls to y={EDGE_Y:.1f} at the edges")
    print(f"               {(EDGE_Y - APEX_Y):.0f} units of fall across the frame, "
          f"12 at the word's flank")
    print(f"holes          {HOLES} on the full circle, pitch {PITCH:.2f} units")
    print(f"svg            {len(svg.encode()):,} bytes  "
          f"(gzipped {len(gzip.compress(svg.encode(), 9)):,})")
    print(f"written        Source/figures/{out.name}")
